### ISSUE TITLE
[Documentation] One recommended install order?

### ISSUE THREAD

**Issue by rubyFeedback** [morpheus562/Baldurs-Gate-Install-Order-List-Repository#8]
Would it be possible to just recommend one entry as the "ideal" one?

I understand that you may not want to do so, but for new users or
semi-new users this may help save them time if they can just follow
a RECOMMENDED installation order. For instance, I recently installed
about 20 mods, but after creating the character, I only see the hand
and then nothing. So now I have no idea at which point I did something
wrong (some mods failed with an installation error; I just have no idea
how to resolve anything there).

**Comment by morpheus562** [comment]
I, and no one else, is capable of stating "this is the ideal mod setup list". It's all personal and we all have different tastes and preferences. If you are having issues with your install order, I recommend reaching out in either the G3 discord or forums and there are many knowledgeable individuals who would be happy to assist you.

**Comment by realAzazello** [comment]
> Would it be possible to just recommend one entry as the "ideal" one?
> 
> I understand that you may not want to do so, but for new users or semi-new users this may help save them time if they can just follow a RECOMMENDED installation order.

There is and has always been a RECOMMENDED install order but it's way more generic - and rightfully so: it's based on mod categories.

```
Fixpack / Corrections
Quests
Tactical encounters
Stores & Items
NPCs
"mini-mods"
'AI' (Tactics) / Rule sets
Spells
Kits
Tweaks
Final Wrap-ups (more corrections, extra tweaks, animations, music, pics, icons, GUIs, etc!)
```
This standard is followed by all install guides out there, BG1 only, BG2 only, BGT, Tutu, EET, etc.


Together with this set of advice **_especially for newbies_**: **Install _One and Only One_**
```
Fixpack mod
Quest mod
```

This keeps the install list simple; reduces chances of errors both when trying to install and play; easily for people to help you troubleshoot problems during play.
